n = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(n))
print('É um número?', n.isnumeric())
print('É um digito?', n.isdigit())
print('É uma letra?', n.isalpha())
print('É um espaço?', n.isspace())
print('São caracteres minusculos?', n.islower())
print('São caracteres maiusculos?', n.isupper())
print('Está captalizada?', n.istitle())
