print('{}-=-'.format('\033[32m') * 11)
print('     Analizador de caracteres')
print('-=-' * 11)
v = input('{}Digite algo: '.format('\033[33m'))
print('{}Tipo desse valor é {}'.format('\033[34m', type(v)))
print('Só tem espaços? {}'.format(v.isspace()))
print('É um número? {}'.format(v.isnumeric()))
print('É alfabético? {}'.format(v.isalpha()))
print('É alfanumérico? {}'.format(v.isalnum()))
print('Está em maiúsculas? {}'.format(v.isupper()))
print('Está em minúsculas? {}'.format(v.islower()))
print('Está captalizada? {}'.format(v.istitle()))
